tinyMCE.addI18n('ru.media_dlg',{
title:"Вставить/редактировать медиа-объект",
general:"Общие",
advanced:"Дополнительные",
file:"Файл/адрес",
list:"Список",
size:"Размеры",
preview:"Предварительный просмотр",
constrain_proportions:"Сохранять пропорции",
type:"Тип",
id:"Идентификатор",
name:"Название",
class_name:"Класс",
vspace:"Вертикальный отступ",
hspace:"Горизонтальный отступ",
play:"Проигрывать автоматически",
loop:"Зациклить",
menu:"Отобразить меню",
quality:"Качество",
scale:"Масштаб",
align:"Выравнивание",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Фон",
base:"Основа",
flashvars:"Переменные Flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Кеш",
hidden:"Скрытое",
controller:"Контроллер",
kioskmode:"Режим киоска",
playeveryframe:"Проигрывать каждый фрейм",
targetcache:"Кеш цели",
correction:"Без исправлений",
enablejavascript:"Включить JavaScript",
starttime:"Время старта",
endtime:"Время окончания",
href:"Href",
qtsrcchokespeed:"Уменьшенная скорость",
target:"Цель",
volume:"Громкость",
autostart:"Автоматическое включение",
enabled:"Включен",
fullscreen:"Полноэкранный режим",
invokeurls:"Вызвать URLs",
mute:"Приглушить",
stretchtofit:"Настроить для соответствия",
windowlessvideo:"Видео без окон",
balance:"Баланс",
baseurl:"Базовый URL",
captioningid:"Идентификатор ввода субтитров",
currentmarker:"Текущий маркер",
currentposition:"Текущая позиция",
defaultframe:"Фрейм по умолчанию",
playcount:"Включить счетчик",
rate:"Норма",
uimode:"UI режим",
flash_options:"Flash опции",
qt_options:"Quicktime опции",
wmp_options:"Windows media player опции",
rmp_options:"Real media player опции",
shockwave_options:"Shockwave опции",
autogotourl:"Автопереход URL",
center:"Центр",
imagestatus:"Статус изображения",
maintainaspect:"Поддержать аспект",
nojava:"Без java",
prefetch:"Предпросмотр",
shuffle:"Случайный порядок",
console:"Консоль",
numloop:"Номер цикла",
controls:"Управление",
scriptcallbacks:"Подстройка скрипта",
swstretchstyle:"Подстройка стиля",
swstretchhalign:"Подстройка горизонтального выравнивания",
swstretchvalign:"Подстройка вертикального выравнивания",
sound:"Звук",
progress:"Выполнено",
qtsrc:"QT Src",
qt_stream_warn:"Проигранный rtsp-ресурс должен быть добавлен к QT Src полю под дополнительной вкладкой.Также Вы должны добавить к Src полю не проигранную версию.",
align_top:"Вверх",
align_right:"Вправо",
align_bottom:"Вниз",
align_left:"Влево",
align_center:"По центру",
align_top_left:"Вверху слева",
align_top_right:"Вверху справа",
align_bottom_left:"Внизу слева",
align_bottom_right:"Внизу справа",
flv_options:"Flash-видео опции",
flv_scalemode:"Режим масштаба",
flv_buffer:"Буффер",
flv_starttime:"Включить время",
flv_defaultvolume:"Громкость по умолчанию",
flv_hiddengui:"Скрытый GUI",
flv_autostart:"Автоматический запуск",
flv_loop:"Зациклить",
flv_showscalemodes:"Показать режим масштаба",
flv_smoothvideo:"Сглаживание видео",
flv_jscallback:"JS отзыв",
html5_video_options:"Настройки видео HTML5",
altsource1:"Альтернативный источник 1",
altsource2:"Альтернативный источник 2",
preload:"Предзагрузка",
poster:"Постер",

source:"Источник"
});