tinyMCE.addI18n('ru.fullpage_dlg',{
title:"Свойства документа",
meta_tab:"Основные",
appearance_tab:"Офомление",
advanced_tab:"Расширенные",
meta_props:"Мета информация",
langprops:"Язык и кодировка",
meta_title:"Заголовок",
meta_keywords:"Ключевые слова",
meta_description:"Описание",
meta_robots:"Роботы",
doctypes:"Тип документа",
langcode:"Код языка",
langdir:"Направление языка",
ltr:"Слева направо",
rtl:"Справа налево",
xml_pi:"Определения XML",
encoding:"Кодировка символов",
appearance_bgprops:"Свойства фона",
appearance_marginprops:"Поля страницы",
appearance_linkprops:"Цвета ссылок",
appearance_textprops:"Свойства текста",
bgcolor:"Цвет фона",
bgimage:"Фоновое изображение",
left_margin:"Левое поле",
right_margin:"Правое поле",
top_margin:"Верхнее поле",
bottom_margin:"Нижнее поле",
text_color:"Цвет текста",
font_size:"Размер шрифта",
font_face:"Гарнитура",
link_color:"Цвет ссылки",
hover_color:"Цвет при наведении",
visited_color:"Цвет посещенной",
active_color:"Цвет активной",
textcolor:"Цвет",
fontsize:"Размер шрифта",
fontface:"Гарнитура",
meta_index_follow:"Индексировать и следовать",
meta_index_nofollow:"Индексировать и не следовать",
meta_noindex_follow:"Не индексировать но следовать",
meta_noindex_nofollow:"Не индексировать и не следовать",
appearance_style:"Таблица стилей и свойства",
stylesheet:"Таблица стилей",
style:"Стиль",
author:"Автор",
copyright:"Права",
add:"Добавить элемент",
remove:"Удалить выделенный элемент",
moveup:"Поднять выделенный элемент",
movedown:"Опустить выделенный элемент",
head_elements:"Заголовочные элементы",
info:"Информация",
add_title:"Заголовок",
add_meta:"Мета-элемент",
add_script:"Скрипт",
add_style:"Стиль",
add_link:"Ссылка",
add_base:"Базовый элемент",
add_comment:"Комментарий",
title_element:"Заголовок",
script_element:"Скрипт",
style_element:"Стиль",
base_element:"Базовый элемент",
link_element:"Ссылка",
meta_element:"Мета-элемент",
comment_element:"Комментарий",
src:"Источник",
language:"Язык",
href:"Адрес ссылки",
target:"Цель",
type:"Тип",
charset:"Кодировка",
defer:"Defer",
media:"Медиа",
properties:"Свойства",
name:"Имя",
value:"Значение",
content:"Содержание",
rel:"Связь",
rev:"Рев.",
hreflang:"Язык ссылки",
general_props:"Основные",
advanced_props:"Расширенные"
});