tinyMCE.addI18n('ru.style_dlg',{
title:"Стиль оформления",
apply:"Применить",
text_tab:"Текст",
background_tab:"Фон",
block_tab:"Блок",
box_tab:"Контейнер",
border_tab:"Граница",
list_tab:"Список",
positioning_tab:"Позиция",
text_props:"Текст",
text_font:"Шрифт",
text_size:"Размер",
text_weight:"Плотность",
text_style:"Стиль",
text_variant:"Начертание",
text_lineheight:"Высота строки",
text_case:"Регистр",
text_color:"Цвет",
text_decoration:"Оформление",
text_overline:"Надчеркнутый",
text_underline:"Подчеркнутый",
text_striketrough:"Зачеркнутый",
text_blink:"Мигающий",
text_none:"Отсутствует",
background_color:"Цвет фона",
background_image:"Фоновое изображение",
background_repeat:"Повторение",
background_attachment:"Прикрепление",
background_hpos:"Горизонтальная позиция",
background_vpos:"Вертикальная позиция",
block_wordspacing:"Промежутки между словами",
block_letterspacing:"Промежутки между символами",
block_vertical_alignment:"Вертикальное выравнивание",
block_text_align:"Выравнивание текста",
block_text_indent:"Отступ текста",
block_whitespace:"Пробел",
block_display:"Отображение",
box_width:"Ширина",
box_height:"Высота",
box_float:"Плавающий",
box_clear:"Очистить",
padding:"Отступ",
same:"Одно значение",
top:"Сверху",
right:"Справа",
bottom:"Снизу",
left:"Слева",
margin:"Поля",
style:"Стиль",
width:"Ширина",
height:"Высота",
color:"Цвет",
list_type:"Тип",
bullet_image:"Изображение маркера",
position:"Позиция",
positioning_type:"Тип",
visibility:"Видимость",
zindex:"Z-индекс",
overflow:"Обтекание",
placement:"Позиция",
clip:"Кадрирование",
text:"Текст",
background:"Фон",
block:"Блок",
box:"Контейнер",
border:"Граница",
list:"Список",
position:"Позиция"
});